services:
  backend:
    build: ./micro-services/backend
    ports:
      - "5000:5000"
    env_file:
      - "./micro-services/backend/.env"
    volumes:
      - ./micro-services/backend:/app
    command: npm run dev
    depends_on:
      - mongo
      - redis
    networks:
      - lms-network
    
  code-executor:
    build: ./micro-services/code-executor
    ports:
      - "7000:7000"
    env_file:
      - "./micro-services/code-executor/.env"
    volumes:
      - ./micro-services/code-executor:/app
    command: npm run dev
    depends_on:
      - backend
      - redis
      - mongo
    networks:
      - lms-network
  mongo:
    image: mongo:6
    ports:
      - "27018:27017"
    env_file:
      - "./.env"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodata:/data/db
    networks:
      - lms-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - lms-network

volumes:
  mongodata:
  redisdata:

networks:
  lms-network:
    driver: bridge

